version: "3"

services:
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./_docker/nginx:/etc/nginx/conf.d
      - ./logs:/www/telegram/logs
    depends_on:
      - app

  python: &base_app # restart: always
    build:
      context: .
      dockerfile: _docker/python/Dockerfile
    volumes:
      - ./:/www/telegram

    depends_on:
      - postgres

  app:
    <<: *base_app
    restart: always
    command: "uvicorn src.main:app --workers 4 --host 0.0.0.0 --port 8000 --root-path /api/v1"
    depends_on:
      - python

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - telegrampgdata:/var/lib/postgresql/data

  frontend: # Add the frontend service for Vue.js
    image: node:latest
    working_dir: /www/vueapp
    volumes:
      - ./client:/www/vueapp # Mount the Vue.js application directory
    command: "npm run serve" # Command to start the development server

volumes:
  telegrampgdata:
    external: true
