"""init

Revision ID: 419ee61940f6
Revises: 
Create Date: 2023-07-02 16:19:32.193818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '419ee61940f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('phone_hash', sa.String(), nullable=True),
    sa.Column('auth', sa.Boolean(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id')
    )
    op.create_table('chat_to_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_chat_id', sa.Integer(), nullable=True),
    sa.Column('to_chat_id', sa.Integer(), nullable=True),
    sa.Column('last_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['from_chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_to_chat')
    op.drop_table('chats')
    op.drop_table('users')
    op.drop_table('accounts')
    # ### end Alembic commands ###
